### ISSUE TITLE
Gulp Serve Fails (again)

### ISSUE THREAD

**Issue by jascination** [flatlogic/angular-material-dashboard#12]
There is another issue raised that was marked as closed from a few months ago. On a fresh build + `npm install`, I get the following error when running `gulp`:

```
[20:58:05] gulp-inject 2 files into index.scss.

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn sass ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

This is remedied by changing line 41 of /gulp/styles.js to:

```
.pipe($.rubySass(sassOptions)
      .on('error', function (err) {
        console.error('Error!', err.message);
     })
    )
```

**Comment by Mystec** [comment]
Thanks for fixing this!

**Comment by shoudaos** [comment]
Fixed. Thanks for proposal
