### ISSUE TITLE
gulp serve fails

### ISSUE THREAD

**Issue by huseyinkozan** [flatlogic/angular-material-dashboard#4]
Hi,
I added gulp-debug to tryo to track the problem but I am not familiar with this error. 
```
 $ gulp serve --verbose  
[13:24:57] Using gulpfile ~/indir/github/angular-material-dashboard/gulpfile.js
[13:24:57] Starting 'styles'...
[13:24:58] gulp-inject 2 files into index.scss.
[13:24:58] gulp-ruby-sass: Running command: sass --style expanded --update /tmp/gulp-ruby-sass:/tmp/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01ce9 --load-path src/app

events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: spawn sass ENOENT
    at exports._errnoException (util.js:844:11)
    at Process.ChildProcess._handle.onexit (child_process.js:987:32)
    at onErrorNT (child_process.js:1138:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
```

I am using iojs:
```
 $ node --version
v2.0.2
```

**Comment by huseyinkozan** [comment]
Fixed after adding on error function.

```js
    .pipe($.rubySass(sassOptions)
      .on('error', function (err) {
        console.error('Error!', err.message);
     })
    )
```

**Comment by huseyinkozan** [comment]
Related;
http://stackoverflow.com/questions/29891814/gulp-ruby-sass-erroring-even-though-css-file-is-empty
