### ISSUE TITLE
Issue encountered while gulp build

### ISSUE THREAD

**Issue by trailingend1992** [flatlogic/angular-material-dashboard#43]
Hi I tried to downloaded it and run it locally.
I encountered the following issue: 
CssSyntaxError in plugin 'gulp-autoprefixer'
Message:
   ../angular-material-dashboard/index.css.map:3:1: Unknown word
Details:
    reason: Unknown word
    ../angular-material-dashboard/index.css.map

Thanks in advance!

**Comment by angelxmoreno** [comment]
Having the same issue. @trailingend1992 did you ever get pass this?

**Comment by trailingend1992** [comment]
It turns out to be the office firewall blocking Git requests... >.<

**Comment by lvnilesh** [comment]
I am running into the same issue.

**Comment by angelxmoreno** [comment]
@trailingend1992 I am not behind a firewall

**Comment by trailingend1992** [comment]
@angelxmoreno @lvnilesh Did you run gulp build before serving it?

**Comment by lvnilesh** [comment]
I think I did
```
[08:30:03] Finished 'build' after 5.73 μs
 ❯❯❯ gulp serve       master
[08:37:14] Using gulpfile /Volumes/3TB/angular-material-dashboard/gulpfile.js
[08:37:14] Starting 'styles'...
[08:37:26] gulp-inject 2 files into index.scss.
[08:37:28] gulp-ruby-sass: directory
[08:37:30] gulp-ruby-sass: write index.css
      write index.css.map
CssSyntaxError in plugin 'gulp-autoprefixer'
Message:
    /Volumes/3TB/angular-material-dashboard/index.css.map:3:1: Unknown word
Details:
    reason: Unknown word
    file: /Volumes/3TB/angular-material-dashboard/index.css.map
    line: 3
    column: 1
    source: {
"version": 3,
"mappings": "AAeA,IAAK;EACH,KAAK,EAdM,OAAO;;;AAiBpB,eAAgB;EACd,SAAS,EAAE,IAAI;;;AAGjB,YAAa;EACX,UAAU,EAAE,MAAM;EAClB,WAAW,EAAE,IAAI;;;AAGnB,aAAc;EACZ,gBAAgB,EA5BF,OAAO;;;AA+BvB,gBAAiB;EACf,KAAK,EAAE,cAAc;EACrB,WAAW,EAAE,IAAI;;;AAKnB,WAAY;EACV,cAAc,EAAE,UAAU;;;AAG5B,WAAY;EACV,MAAM,EAAE,IAAI;EACZ,aAAa,EAAE,GAAG;EAClB,MAAM,EAAE,MAAM;;;AAKhB,SAAU;EACR,QAAQ,EAAE,QAAQ;;AAElB,iBAAU;EACR,MAAM,EAAE,KAAK;;;AAIjB,oBAAqB;EACnB,KAAK,EAAE,IAAI;EACX,MAAM,EAAE,IAAI;EACZ,WAAW,EAAE,IAAI;EACjB,UAAU,EAAE,MAAM;EAClB,aAAa,EAAE,GAAG;EAClB,QAAQ,EAAE,QAAQ;EAClB,SAAS,EAAE,IAAI;EACf,GAAG,EAAE,GAAG;EACR,KAAK,EAAE,GAAG;EACV,gBAAgB,EAjEF,OAAO;;;AAqEvB,aAAc;EACZ,gBAAgB,EAAE,KAAK;;AAEvB,qBAAU;EACR,UAAU,EAAE,IAAI;EAChB,MAAM,EAAE,CAAC;;AAGX,oBAAS;EACP,KAAK,EAhFI,OAAO;;;AAoFpB,QAAS;EACP,kBAAkB,EAAC,eAAe;EAClC,UAAU,EAAC,eAAe;;;AAG5B,gBAAiB;EACf,OAAO,EAAC,CAAC;;;AAGX,oBAAqB;EACnB,MAAM,EAvFQ,KAAK;;;AA2FrB,kBAAkB;EAChB,UAAU,EAAE,MAAM;;;AAGpB,eAAgB;EACd,SAAS,EA9FO,IAAI;EA+FpB,KAAK,EAxGM,OAAO;EAyGlB,UAAU,EAAE,MAAM;;;AAMpB,cAAe;EACb,MAAM,EAAE,IAAI;;;AAGd,OAAQ;EACN,MAAM,EAAE,IAAI;;;AAGd,yCAA0C;EACxC,KAAK,EAlHc,KAAK;EAmHxB,SAAS,EAnHU,KAAK;EAoHxB,SAAS,EApHU,KAAK;;;AAuH1B,kHAAmH;EACjH,KAAK,EAAE,KAAK;;;AAGd,mDAAoD;EAClD,KAAK,EAjIQ,OAAgB;;;AAoI/B,oBAAqB;EACnB,SAAS,EA7HO,IAAI;;;AAiItB,+BAAgC;EAC9B,QAAQ,EAAE,KAAK;;;AAIjB,eAAgB;EACd,cAAc,EAAE,MAAM;;;AAGxB,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AACvC,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AACvC,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AACvC,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AAEvC,0BAA2B;EACzB,IAAI,EAAE,OAAe;EACrB,WAAW,EAlJM,GAAG;EAmJpB,SAAS,EAAE,eAA2B;;;AAGxC,UAAW;EACT,gBAAgB,EAAE,WAAW;EAC7B,MAAM,EAAE,IAAI;EACZ,WAAW,EAzJM,GAAG;;;AA4JtB,gBAAiB;EACf,gBAAgB,EAAE,MAAM;;;AAG1B,qBAAsB;EACpB,gBAAgB,EAAE,OACpB;;;AClJA,MAAO;EACL,cAAc,EAAE,CAAC;EACjB,KAAK,EAAE,IAAI;EACX,SAAS,EAAE,IAAI;EACf,aAAa,EAAE,IAAI;EACnB,gBAAgB,EAvBc,IAAI;;AA2BhC;;mBAAK;EAlBP,kBAAkB,EAAE,aAA6C;EACjE,eAAe,EAAE,aAA6C;EAC9D,cAAc,EAAE,aAA6C;EAC7D,aAAa,EAAE,aAA6C;EAC5D,UAAU,EAAE,aAA6C;;AAgBrD;;;;;wBACK;EACH,UAAU,EAAE,IAAI;EAChB,OAAO,EAlCiB,MAAM;EAmC9B,cAAc,EAAE,GAAG;EACnB,UAAU,EAAE,CAAC;EAzBnB,kBAAkB,EAAE,aAA6C;EACjE,eAAe,EAAE,aAA6C;EAC9D,cAAc,EAAE,aAA6C;EAC7D,aAAa,EAAE,aAA6C;EAC5D,UAAU,EAAE,aAA6C;;AA0BzD,wBAAkB;EAChB,WAAW,EA7CiB,GAAG;EA8C/B,KAAK,EA7CuB,OAAO;EA8CnC,cAAc,EAAE,MAAM;EACtB,aAAa,EAAE,6BAAyB;;AAMtC;;;;;gDACK;EACH,UAAU,EAAE,CAAC;;AAInB,sBAAgB;EACd,UAAU,EAAE,6BAAyB;;AAIvC,aAAO;EACL,gBAAgB,EA7DY,IAAI;;AAiElC,iBAAW;EACT,MAAM,EAAE,CAAC;;;AAOb,eAAgB;EACd,MAAM,EAAE,CAAC;;AAKL;;;;;iCACK;EACH,MAAM,EAAE,CAAC;EACT,aAAa,EAAE,iBAA6B;;AAKhD;iCACK;EACH,mBAAmB,EAAE,GAAG;;;AAU1B;oCACK;EACH,gBAAgB,EAlGU,mBAAe;;;AA8G7C,oCAAqC;EAGnC,mCAAS;IACP,aAAa,EAAE,CAAC;IAChB,gBAAgB,EAAE,WAAW;;EAC7B;6CACQ;IACN,OAAO,EAAE,IAAI;;EAGf,2CAAQ;IACN,OAAO,EAAE,KAAK;;EAEd,gDAAK;IACH,OAAO,EAAE,KAAK;IACd,MAAM,EAAE,iBAA6B;IACrC,aAAa,EAAE,GAAG;IAClB,aAAa,EArIS,MAAM;;EAuI5B,qDAAK;IACH,gBAAgB,EAtII,IAAI;IAuIxB,OAAO,EAAE,KAAK;IACd,cAAc,EAAE,MAAM;IACtB,UAAU,EAAE,KAAK;;EAEnB,wEAAwB;IACtB,OAAO,EAAE,gBAAgB;IACzB,KAAK,EAAE,IAAI;IACX,SAAS,EAAE,OAAO;IAClB,WAAW,EApJS,GAAG;IAqJvB,KAAK,EApJe,OAAO;IAqJ3B,aAAa,EAAE,IAAI;;EAO3B,qCAAa;IACX,kBAAkB,EAAE,IAAI;IACxB,eAAe,EAAE,IAAI;IACrB,UAAU,EAAE,IAAI;;EAChB,2DAAsB;IACpB,MAAM,EAAE,IAAI;;EAKhB,4CAAkB;IAChB,MAAM,EAAE,CAAC;;EAKL,8DAAK;IACH,MAAM,EAAE,CAAC;IACT,aAAa,EAAE,iBAA6B;;EAE9C,yEAAgB;IACd,aAAa,EAAE,CAAC;;EAQtB;yEAC4B;IAC1B,gBAAgB,EAvLQ,IAAI;;EAyL9B,4EAAiC;IAC/B,gBAAgB,EAzLQ,OAAO;;EAgM/B;8DACW;IACT,gBAAgB,EAnMM,IAAI;;EAqM5B,iEAAgB;IACd,gBAAgB,EAnMM,mBAAe",
"sources": ["../../../../../../../Volumes/3TB/angular-material-dashboard/src/app/stylesheets/_custom.scss","../../../../../../../Volumes/3TB/angular-material-dashboard/src/app/stylesheets/_table.scss"],
"names": [],
"file": "index.css"
}
    fileName: /var/folders/7y/gygjl_19011877dq85p6lw5r0000gn/T/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01ce9/index.css.map
[08:37:30] Finished 'styles' after 16 s
[08:37:30] Starting 'inject'...
[08:37:30] gulp-inject 1 files into 404.html.
[08:37:30] gulp-inject 1 files into index.html.
[08:37:31] gulp-inject 22 files into 404.html.
[08:37:32] gulp-inject 22 files into index.html.
[08:37:32] Finished 'inject' after 2.02 s
[08:37:32] Starting 'watch'...
[08:37:32] Finished 'watch' after 46 ms
[08:37:32] Starting 'serve'...
[08:37:37] Finished 'serve' after 4.56 s
[BS] Local URL: http://localhost:3000/
[BS] External URL: http://10.0.1.7:3000/
[BS] Serving files from: .tmp/serve
[BS] Serving files from: src
[BS] Watching files...
```

**Comment by trailingend1992** [comment]
@lvnilesh hmmm... Try to remove node modules and run npm build again?

**Comment by angelxmoreno** [comment]
@trailingend1992 I get this issue _while_ running `gulp build`

**Comment by TheOtherRealm** [comment]
in `npm-debug.log` I am getting

```
...
67 verbose stack RangeError: Maximum call stack size exceeded
67 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/actions.js:54:33
67 verbose stack     at Array.forEach (native)
67 verbose stack     at markAsFailed (/usr/local/lib/node_modules/npm/lib/install/actions.js:54:16)
67 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/actions.js:57:7
67 verbose stack     at Array.forEach (native)
67 verbose stack     at markAsFailed (/usr/local/lib/node_modules/npm/lib/install/actions.js:54:16)
67 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/actions.js:57:7
67 verbose stack     at Array.forEach (native)
67 verbose stack     at markAsFailed (/usr/local/lib/node_modules/npm/lib/install/actions.js:54:16)
67 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/actions.js:57:7
68 verbose cwd /var/www/html/theotherrealm/othermind/app
69 error Linux 3.13.0-042stab111.12
70 error argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "--unsafe-perm" "--allow-root"
71 error node v4.4.4
72 error npm  v3.8.6
73 error Maximum call stack size exceeded
74 error If you need help, you may report this error at:
74 error     <https://github.com/npm/npm/issues>
```

**Comment by uncledlm** [comment]
I modified gulp/styles.js 

Line 11 sassOptions

  var sassOptions = {
    style: 'expanded',
    'sourcemap=none': true
  };

**Comment by angelxmoreno** [comment]
@uncledlm if that is a fix, could you please submit a PR?

**Comment by micrum** [comment]
thank you all guys for the reporting, @uncledlm thanks a lot for the PR. Merged
