### ISSUE TITLE
Error: Error: jquery is not installed. Try running `bower install`. / CssSyntaxError in plugin 'gulp-autoprefixer'

### ISSUE THREAD

**Issue by TheOtherRealm** [flatlogic/angular-material-dashboard#46]
Getting this issue while trying to build on my ubuntu 14.04 server:
I ran 'bower install' but it did not change anything and jQuery is in my dependencies, I believe

```
.../app/# gulp serve
[14:11:47] Using gulpfile /var/www/html/theotherrealm/othermind/app/gulpfile.js
[14:11:47] Starting 'styles'...
[14:11:47] gulp-inject 2 files into index.scss.
[14:11:47] gulp-ruby-sass: stderr: DEPRECATION WARNING:
Sass 3.5 will no longer support Ruby 1.9.3.
Please upgrade to Ruby 2.0.0 or greater as soon as possible.
[14:11:47] gulp-ruby-sass: stderr:
[14:11:47] gulp-ruby-sass: directory
[14:11:48] gulp-ruby-sass: write index.css
      write index.css.map
CssSyntaxError in plugin 'gulp-autoprefixer'
Message:
    /var/www/html/theotherrealm/othermind/app/index.css.map:3:1: Unknown word
Details:
    reason: Unknown word
    file: /var/www/html/theotherrealm/othermind/app/index.css.map
    line: 3
    column: 1
    source: {
"version": 3,
"mappings": "AAeA,IAAK;EACH,KAAK,EAdM,OAAO;;;AAiBpB,eAAgB;EACd,SAAS,EAAE,IAAI;;;AAGjB,YAAa;EACX,UAAU,EAAE,MAAM;EAClB,WAAW,EAAE,IAAI;;;AAGnB,aAAc;EACZ,gBAAgB,EA5BF,OAAO;;;AA+BvB,gBAAiB;EACf,KAAK,EAAE,cAAc;EACrB,WAAW,EAAE,IAAI;;;AAKnB,WAAY;EACV,cAAc,EAAE,UAAU;;;AAG5B,WAAY;EACV,MAAM,EAAE,IAAI;EACZ,aAAa,EAAE,GAAG;EAClB,MAAM,EAAE,MAAM;;;AAKhB,SAAU;EACR,QAAQ,EAAE,QAAQ;;AAElB,iBAAU;EACR,MAAM,EAAE,KAAK;;;AAIjB,oBAAqB;EACnB,KAAK,EAAE,IAAI;EACX,MAAM,EAAE,IAAI;EACZ,WAAW,EAAE,IAAI;EACjB,UAAU,EAAE,MAAM;EAClB,aAAa,EAAE,GAAG;EAClB,QAAQ,EAAE,QAAQ;EAClB,SAAS,EAAE,IAAI;EACf,GAAG,EAAE,GAAG;EACR,KAAK,EAAE,GAAG;EACV,gBAAgB,EAjEF,OAAO;;;AAqEvB,aAAc;EACZ,gBAAgB,EAAE,KAAK;;AAEvB,qBAAU;EACR,UAAU,EAAE,IAAI;EAChB,MAAM,EAAE,CAAC;;AAGX,oBAAS;EACP,KAAK,EAhFI,OAAO;;;AAoFpB,QAAS;EACP,kBAAkB,EAAC,eAAe;EAClC,UAAU,EAAC,eAAe;;;AAG5B,gBAAiB;EACf,OAAO,EAAC,CAAC;;;AAGX,oBAAqB;EACnB,MAAM,EAvFQ,KAAK;;;AA2FrB,kBAAkB;EAChB,UAAU,EAAE,MAAM;;;AAGpB,eAAgB;EACd,SAAS,EA9FO,IAAI;EA+FpB,KAAK,EAxGM,OAAO;EAyGlB,UAAU,EAAE,MAAM;;;AAMpB,cAAe;EACb,MAAM,EAAE,IAAI;;;AAGd,OAAQ;EACN,MAAM,EAAE,IAAI;;;AAGd,yCAA0C;EACxC,KAAK,EAlHc,KAAK;EAmHxB,SAAS,EAnHU,KAAK;EAoHxB,SAAS,EApHU,KAAK;;;AAuH1B,kHAAmH;EACjH,KAAK,EAAE,KAAK;;;AAGd,mDAAoD;EAClD,KAAK,EAjIQ,OAAgB;;;AAoI/B,oBAAqB;EACnB,SAAS,EA7HO,IAAI;;;AAiItB,+BAAgC;EAC9B,QAAQ,EAAE,KAAK;;;AAIjB,eAAgB;EACd,cAAc,EAAE,MAAM;;;AAGxB,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AACvC,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AACvC,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AACvC,qBAAsB;EAAE,SAAS,EAAE,IAAI;;;AAEvC,0BAA2B;EACzB,IAAI,EAAE,OAAe;EACrB,WAAW,EAlJM,GAAG;EAmJpB,SAAS,EAAE,eAA2B;;;AAGxC,UAAW;EACT,gBAAgB,EAAE,WAAW;EAC7B,MAAM,EAAE,IAAI;EACZ,WAAW,EAzJM,GAAG;;;AA4JtB,gBAAiB;EACf,gBAAgB,EAAE,MAAM;;;AAG1B,qBAAsB;EACpB,gBAAgB,EAAE,OACpB;;;AClJA,MAAO;EACL,cAAc,EAAE,CAAC;EACjB,KAAK,EAAE,IAAI;EACX,SAAS,EAAE,IAAI;EACf,aAAa,EAAE,IAAI;EACnB,gBAAgB,EAvBc,IAAI;;AA2BhC;;mBAAK;EAlBP,kBAAkB,EAAE,aAA6C;EACjE,eAAe,EAAE,aAA6C;EAC9D,cAAc,EAAE,aAA6C;EAC7D,aAAa,EAAE,aAA6C;EAC5D,UAAU,EAAE,aAA6C;;AAgBrD;;;;;wBACK;EACH,UAAU,EAAE,IAAI;EAChB,OAAO,EAlCiB,MAAM;EAmC9B,cAAc,EAAE,GAAG;EACnB,UAAU,EAAE,CAAC;EAzBnB,kBAAkB,EAAE,aAA6C;EACjE,eAAe,EAAE,aAA6C;EAC9D,cAAc,EAAE,aAA6C;EAC7D,aAAa,EAAE,aAA6C;EAC5D,UAAU,EAAE,aAA6C;;AA0BzD,wBAAkB;EAChB,WAAW,EA7CiB,GAAG;EA8C/B,KAAK,EA7CuB,OAAO;EA8CnC,cAAc,EAAE,MAAM;EACtB,aAAa,EAAE,6BAAyB;;AAMtC;;;;;gDACK;EACH,UAAU,EAAE,CAAC;;AAInB,sBAAgB;EACd,UAAU,EAAE,6BAAyB;;AAIvC,aAAO;EACL,gBAAgB,EA7DY,IAAI;;AAiElC,iBAAW;EACT,MAAM,EAAE,CAAC;;;AAOb,eAAgB;EACd,MAAM,EAAE,CAAC;;AAKL;;;;;iCACK;EACH,MAAM,EAAE,CAAC;EACT,aAAa,EAAE,iBAA6B;;AAKhD;iCACK;EACH,mBAAmB,EAAE,GAAG;;;AAU1B;oCACK;EACH,gBAAgB,EAlGU,mBAAe;;;AA8G7C,oCAAqC;EAGnC,mCAAS;IACP,aAAa,EAAE,CAAC;IAChB,gBAAgB,EAAE,WAAW;;EAC7B;6CACQ;IACN,OAAO,EAAE,IAAI;;EAGf,2CAAQ;IACN,OAAO,EAAE,KAAK;;EAEd,gDAAK;IACH,OAAO,EAAE,KAAK;IACd,MAAM,EAAE,iBAA6B;IACrC,aAAa,EAAE,GAAG;IAClB,aAAa,EArIS,MAAM;;EAuI5B,qDAAK;IACH,gBAAgB,EAtII,IAAI;IAuIxB,OAAO,EAAE,KAAK;IACd,cAAc,EAAE,MAAM;IACtB,UAAU,EAAE,KAAK;;EAEnB,wEAAwB;IACtB,OAAO,EAAE,gBAAgB;IACzB,KAAK,EAAE,IAAI;IACX,SAAS,EAAE,OAAO;IAClB,WAAW,EApJS,GAAG;IAqJvB,KAAK,EApJe,OAAO;IAqJ3B,aAAa,EAAE,IAAI;;EAO3B,qCAAa;IACX,kBAAkB,EAAE,IAAI;IACxB,eAAe,EAAE,IAAI;IACrB,UAAU,EAAE,IAAI;;EAChB,2DAAsB;IACpB,MAAM,EAAE,IAAI;;EAKhB,4CAAkB;IAChB,MAAM,EAAE,CAAC;;EAKL,8DAAK;IACH,MAAM,EAAE,CAAC;IACT,aAAa,EAAE,iBAA6B;;EAE9C,yEAAgB;IACd,aAAa,EAAE,CAAC;;EAQtB;yEAC4B;IAC1B,gBAAgB,EAvLQ,IAAI;;EAyL9B,4EAAiC;IAC/B,gBAAgB,EAzLQ,OAAO;;EAgM/B;8DACW;IACT,gBAAgB,EAnMM,IAAI;;EAqM5B,iEAAgB;IACd,gBAAgB,EAnMM,mBAAe",
"sources": ["../../../var/www/html/theotherrealm/othermind/app/src/app/stylesheets/_custom.scss","../../../var/www/html/theotherrealm/othermind/app/src/app/stylesheets/_table.scss"],
"names": [],
"file": "index.css"
}
    fileName: /tmp/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01ce9/index.css.map
[14:11:48] Finished 'styles' after 1.06 s
[14:11:48] Starting 'inject'...
[14:11:48] gulp-inject 1 files into 404.html.
[14:11:48] gulp-inject 1 files into index.html.
[14:11:48] gulp-inject 22 files into 404.html.
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: Error: jquery is not installed. Try running `bower install`.
    at /var/www/html/theotherrealm/othermind/app/node_modules/wiredep/wiredep.js:30:56
    at /var/www/html/theotherrealm/othermind/app/node_modules/wiredep/lib/detect-dependencies.js:145:29
    at forOwn (/var/www/html/theotherrealm/othermind/app/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/var/www/html/theotherrealm/othermind/app/node_modules/lodash/dist/lodash.js:3303:9)
    at detectDependencies (/var/www/html/theotherrealm/othermind/app/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/var/www/html/theotherrealm/othermind/app/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/var/www/html/theotherrealm/othermind/app/node_modules/wiredep/wiredep.js:135:34)
    at DestroyableTransform.Transform._read (/var/www/html/theotherrealm/othermind/app/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/www/html/theotherrealm/othermind/app/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/var/www/html/theotherrealm/othermind/app/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:237:10)

```

**Comment by TheOtherRealm** [comment]
installing using
```
npm install  --unsafe-perm
bower build --allow-root
```
solved the: `Error: jquery is not installed` issue but the `CssSyntaxError ` issue remains.  Closing this issue because there is another ticket already open which deals with that.
