### ISSUE TITLE
gulp buld does not work

### ISSUE THREAD

**Issue by ggunders** [flatlogic/angular-material-dashboard#50]
gulp build
[12:47:51] Using gulpfile ~/Projects/angular-material-dashboard/gulpfile.js
[12:47:51] Starting 'clean'...
[12:47:51] Finished 'clean' after 27 ms
[12:47:51] Starting 'default'...
[12:47:51] Starting 'styles'...
[12:47:52] Starting 'partials'...
[12:47:52] Starting 'images'...
[12:47:52] Starting 'fonts'...
[12:47:52] Starting 'misc'...
[12:47:52] Finished 'default' after 371 ms
[12:47:52] gulp-inject 2 files into index.scss.
[12:47:52] Finished 'misc' after 96 ms
[12:47:52] Finished 'images' after 160 ms
[12:47:52] Finished 'fonts' after 178 ms
fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/Users/XXXX/Projects/angular-material-dashboard/src/templateCacheHtml.js'
    at
at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at DestroyableTransform.TransformStream [as _transform](/Users/XXXX/Projects/angular-material-dashboard/node_modules/gulp-header/index.js:38:12)

**Comment by gavingregory** [comment]
No problem on Linux, but recreated the error on a Windows machine. A temporary fix is to create the file manually.

from project directory:
`cd src/
touch templateCacheHtml.js`
(from git bash, on windows).

**Comment by DimaSavchenko** [comment]
@gavingregory, Thanks for your proposal !
