### ISSUE TITLE
require.extensions.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by De-Lac** [flatlogic/angular-material-dashboard#68]
I've got this error when run `gulp serve`

```
$ gulp serve
./website/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (./website/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Volumes/HD Daniele/Sites/PennyCell/website/gulpfile.js:12:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
```
my system
```
$ npm --version
5.3.0

node --version
v8.1.3
```

**Comment by reyco1** [comment]
I'm having the same issue.... Anyone figure this out?

**Comment by fabionoth** [comment]
I have the same issue

**Comment by stevenhebert** [comment]
updating require-dir to version 0.3.2, _rm -rf node_modules,_ and _npm i_ fixed my build

**Comment by bhargavkn** [comment]
@stevenhebert  this worked for me too, thanks!

**Comment by kennedykinyanjui** [comment]
Did it for me as well. Thanks.
